
export const PAGE_PORTFOLIO = "portfolio"
export const PAGE_ABOUT = "about"
export const PAGE_PRICE = "price"
export const PAGE_CONTACTS = "contacts"
export const PAGE_PROJECT1 = "proj1"
export const PAGE_PROJECT2 = "proj2"
export const PAGE_PROJECT3 = "proj3"
export const PAGE_PROJECT4 = "proj4"
export const PAGE_PROJECT5 = "proj5"
export const PAGE_PROJECT6 = "proj6"
export const PAGE_PROJECT7 = "proj7"
export const PAGE_PROJECT8 = "proj8"
export const PAGE_PROJECT9 = "proj9"